project:
  type: website
  output-dir: docs
  
website:
  title: "Wedding"
  sidebar:
    search: false 
    contents:
      - href: event_info.qmd
      - href: travel_info.qmd
      - href: accomendations.qmd
      - href: registry.qmd
      - href: RSVP.qmd
      - href: dress_code.qmd
      
  page-footer:
    right: ""
    left: "Duncan & Kelsey's Wedding"

format:
  html:
    theme: paper
    mainfont: Georgia
    title-block-banner-color: rgb(193, 123, 11)
    toc: true

editor: source

